===2023-03-20 14:58:53.204 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:70  - OpenAI  sse连接异常data：，异常：{}
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.unfbx.chatgpt.entity.chat.ChatCompletionResponse` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[DONE]"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:648)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:48)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 15:01:37.826 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:70  - OpenAI  sse连接异常data：，异常：{}
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.unfbx.chatgpt.entity.chat.ChatCompletionResponse` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[DONE]"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:648)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:48)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 15:05:00.918 ERROR org.apache.tomcat.util.net.Acceptor Line:175 - Socket accept failed
java.nio.channels.AsynchronousCloseException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:259)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:547)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 15:35:37.524 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:71  - OpenAI  sse连接异常data：，异常：{}
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:198)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:50)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1424)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:768)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:732)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:716)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1266)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 24 common frames omitted
===2023-03-20 15:45:40.639 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:71  - OpenAI  sse连接异常data：，异常：{}
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Protocol wrong type for socket
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:198)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:50)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Protocol wrong type for socket
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1424)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:768)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:732)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:716)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1266)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 24 common frames omitted
===2023-03-20 16:04:29.123 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:71  - OpenAI  sse连接异常data：，异常：{}
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:198)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:50)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1424)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:768)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:732)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:716)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1266)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 24 common frames omitted
===2023-03-20 16:06:10.246 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:71  - OpenAI  sse连接异常data：，异常：{}
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:198)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:50)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1424)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:768)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:732)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:716)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1266)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 24 common frames omitted
===2023-03-20 16:09:53.684 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:71  - OpenAI  sse连接异常data：，异常：{}
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:148)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
	at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
	at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.sendInternal(ResponseBodyEmitterReturnValueHandler.java:212)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.send(ResponseBodyEmitterReturnValueHandler.java:205)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:198)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:127)
	at com.aitrip.chatgpt.listener.OpenAIEventSourceListener.onEvent(OpenAIEventSourceListener.java:50)
	at okhttp3.internal.sse.RealEventSource.onEvent(RealEventSource.kt:101)
	at okhttp3.internal.sse.ServerSentEventReader.completeEvent(ServerSentEventReader.kt:108)
	at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:52)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:469)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1424)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:768)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:732)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:716)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:573)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:221)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1266)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:402)
	at org.apache.coyote.Response.action(Response.java:209)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:306)
	... 24 common frames omitted
===2023-03-20 16:21:00.067 ERROR com.aitrip.chatgpt.listener.OpenAIEventSourceListener Line:71  - OpenAI  sse连接异常data：<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
，异常：null
===2023-03-20 19:11:29.860 ERROR org.apache.tomcat.util.net.Acceptor Line:175 - Socket accept failed
java.nio.channels.AsynchronousCloseException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:259)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:547)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.923 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.922 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.922 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.924 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.925 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.923 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.925 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.927 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.928 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.928 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.927 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.929 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.925 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.924 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.930 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.931 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.931 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.926 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.931 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.925 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.932 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.932 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.932 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.933 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.933 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.933 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.926 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.935 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.936 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.922 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.936 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.937 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.937 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.934 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.937 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.934 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.938 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.937 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.939 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.939 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.937 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.940 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.940 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.941 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.941 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.942 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.922 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.934 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.942 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.938 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.924 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.939 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.943 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.943 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.944 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.944 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.945 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.945 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.946 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.944 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.946 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.944 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.947 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.945 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.947 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.948 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.948 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.954 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.954 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.954 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.956 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.956 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.957 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.957 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.957 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.956 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.958 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.958 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.959 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.959 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.957 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.957 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.959 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.959 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.959 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.958 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.960 ERROR org.apache.tomcat.util.net.NioEndpoint Line:175 - Error running socket processor
java.lang.NullPointerException: null
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.getSelectionKey(NioEndpoint.java:1825)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.957 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.960 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.960 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.962 ERROR org.apache.tomcat.util.net.NioEndpoint Line:175 - Error running socket processor
java.lang.NullPointerException: null
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.getSelectionKey(NioEndpoint.java:1825)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.961 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.963 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.964 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.965 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.966 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.969 ERROR org.apache.tomcat.util.net.NioEndpoint Line:175 - Error running socket processor
java.lang.NullPointerException: null
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.getSelectionKey(NioEndpoint.java:1825)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.966 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:177)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:171)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:438)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:135)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:147)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.969 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.970 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:11:31.970 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:175 - Error during mapping
java.lang.NullPointerException: null
	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:872)
	at org.apache.catalina.mapper.Mapper.map(Mapper.java:726)
	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:473)
	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:225)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:358)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:244)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:329)
	at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:439)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:148)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:11:31.970 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] Line:173 - Custom error page [/error] could not be dispatched correctly
===2023-03-20 19:29:27.472 ERROR org.apache.tomcat.util.net.Acceptor Line:175 - Socket accept failed
java.nio.channels.AsynchronousCloseException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:259)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:547)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.lang.Thread.run(Thread.java:750)
===2023-03-20 19:29:46.675 ERROR org.apache.tomcat.util.net.Acceptor Line:175 - Socket accept failed
java.nio.channels.AsynchronousCloseException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:205)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:259)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:547)
	at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:79)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:129)
	at java.lang.Thread.run(Thread.java:750)
